version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install:
          version: '2.0'
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          rvm-exec 2.0 rake
      - ruby/install:
          version: '2.2'
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          rvm-exec 2.2 rake
      - ruby/install:
          version: '2.4'
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          rvm-exec 2.4 rake
      - ruby/install:
          version: '2.5'
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          rvm-exec 2.5 rake
      - ruby/install:
          version: '2.6'
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          rvm-exec 2.6 rake
      - ruby/install:
          version: '2.7'
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          rvm-exec 2.7 rake


